### ISSUE TITLE
Geolocation on images

### ISSUE THREAD

**Issue by luisjar** [luisjar/Project_4#1]
I'm really confused on how to store the latitude and longitude for each image that the users upload to my app.

Right now the users are being able to upload images from their computers. I'm storing them on S3 and doing this with "paperclip" gem. 

Also, I'm getting the latitude and longitude of the place in which my app is being opened. So what I wish to do is save in my database the latitude and longitude of each image from were it was uploaded but I can't figure out how to do this.

@htella 
@harimohanraj89 
@DrRobotmck

**Comment by htella** [comment]
got this
