### ISSUE TITLE
Uploading images to my server broke

### ISSUE THREAD

**Issue by luisjar** [luisjar/Project_4#2]
@htella 
@harimohanraj89 
@DrRobotmck 

I want the users to upload pictures to my app. I am saving those pictures to Amazon S3 using paperclip. I'm also saving each picture's Longitude and Latitude of the place from were the user uploads the picture. I'm doing that with geocoder. Everything was working well and I just tried uploading a new picture and I am getting back the following error:

NoMethodError (undefined method address=' for #Upload:0x007f8b13194b50):
  app/controllers/uploads_controller.rb:16:increate'

I can't find the problem, I'm attaching the controller and model that I am using for that.

The problem gets fixed when I remove ":latitude, :longitude" from "upload_params", but if I do that I won't be able to save the latitude and longitude for each picture.

Controller

```
class UploadsController < ApplicationController

  def index

    @uploads = Upload.near([request.location.latitude, request.location.longitude], 1)

    # render json: Upload.all.to_json(:methods => [:image_url])
    render json: @uploads.to_json(:methods => [:image_url])
  end

  def new
    @upload = Upload.new
  end

  def create
    @upload = Upload.create(upload_params)
    if @upload.save
      render json: { message: "success" }, :status => 200
    else
      #need to send an error header, otherwise Dropzone
          #  will not interpret the response as an error:
      render json: { error: @upload.errors.full_messages.join(',')}, :status => 400
    end         
  end

  private
  def upload_params
    params.require(:upload).permit(:image, :latitude, :longitude)
  end
end
```

Model

```
class Upload < ActiveRecord::Base
    # geocoded_by :ip_address,
 #      :latitude => :lat, :longitude => :lon
    # after_validation :geocode

    # geocoded_by :address
    # after_validation :geocode

    reverse_geocoded_by :latitude, :longitude
    after_validation :reverse_geocode  # auto-fetch address

    has_attached_file :image, :styles => { :medium => "300x300>",:thumb => "100x100>" }

    validates_attachment    :image, 
                :presence => true,
                :content_type => { :content_type => /\Aimage\/.*\Z/ },
                :size => { :less_than => 2.megabyte }

    def image_url
        image.url
    end
end

```

**Comment by htella** [comment]
reading

**Comment by htella** [comment]
the easy way to fix this, add this method to your upload.rb (model)

``` ruby
def address=(address)
    # ignore address, do nothing
end
```

**Comment by htella** [comment]
let me know if that works for you

**Comment by luisjar** [comment]
That worked @htella. Thank you so much!

**Comment by htella** [comment]
ok so for some reason Geocoder wants to store an address for each upload model. There was no address field for your upload model so it complained that there was no `address=` method. So we made one that does nothing, now no more problem.

**Comment by htella** [comment]
The correct way to fix this is to add a field called `address` for your upload model. You can make an other migration or edit an existing one and then recreate the db. 

If you do it this way you no longer have to add that dummy method to you upload.rb (model)

**Comment by htella** [comment]
Hold off on doing it the second way though. I am testing something out to be sure I'm saying the right thing.
